CREATE DATABASE catalog;
CREATE TABLE
  LABEL(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    COLOR VARCHAR(100) NOT NULL
  );

CREATE TABLE
  book(
    ID SERIAL PRIMARY KEY,
    LABEL_ID INT,
    PUBLISH_DATE DATE NOT NULL,
    ARCHIVED BOOLEAN NOT NULL,
    PUBLISHER VARCHAR(100) NOT NULL,
    COVER_STATE VARCHAR(100) NOT NULL,
    FOREIGN KEY (LABEL_ID) REFERENCES LABEL(ID)
  );

CREATE TABLE
  author(
    ID INT GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    PRIMARY KEY(ID)
  );

CREATE TABLE
  game(
    ID INT GENERATED ALWAYS AS IDENTITY,
    AUTHOR_ID INT,
    PUBLISH_DATE DATE NOT NULL,
    ARCHIVED BOOLEAN NOT NULL,
    MULTIPLAYER VARCHAR(250) NOT NULL,
    LAST_PLAYED_AT DATE NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
  );

CREATE TABLE genre(
    ID  INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE music_album(
    ID GENERATED ALWAYS AS IDENTITY INT,
    GENRE_ID INT,
    PUBLISH_DATE DATE NOT NULL,
    ARCHIVED BOOLEAN NOT NULL,
    name VARCHAR(100),
    ON_SPOTIFY BOOLEAN,
    FOREIGN KEY(GENRE_ID) REFERENCES GENRE(ID)
);
